/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.Cliente;
import controller.MembroGrupo;
import controller.Objetivo;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.ClienteModel;
import model.MembroGrupoModel;
import model.ObjetivoModel;

/**
 *
 * @author silma
 */
public class JFMembroGrupo extends javax.swing.JFrame {
    private ArrayList<Objetivo> objetivos;
    private ArrayList<Cliente> clientes;
    private ArrayList<MembroGrupoModel> associacoes;
    private int linhaSelecionada = -1;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JFMembroGrupo.class.getName());

    /**
     * Creates new form JFMenbroGrupo
     */
    public JFMembroGrupo() {
        initComponents();
        
        cmbObjetivo.setModel(new DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbCliente.setModel(new DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        
        carregarCombos ();
        atualizarTabela();
        controlarBotoes();

        // Listeners para filtro automático
        cmbObjetivo.addActionListener(e -> atualizarTabela());
        cmbCliente.addActionListener(e -> atualizarTabela());
        
    }
    
    //método para carregar os campos da tabela.
    private void carregarCombos() {
        // Carrega objetivos
        ObjetivoModel objModel = new ObjetivoModel();
        objetivos = objModel.liste();
        
        cmbObjetivo.removeAllItems();
        cmbObjetivo.addItem("Todos"); // item para filtro
        for (Objetivo o : objetivos) {
            cmbObjetivo.addItem(o);
        }

        // Carrega clientes
        ClienteModel cliModel = new ClienteModel();
        clientes = cliModel.liste();
        
        cmbCliente.removeAllItems();
        cmbCliente.addItem("Todos");
        for (Cliente c : clientes) {
            cmbCliente.addItem(c);
        }

        cmbObjetivo.setSelectedIndex(0);
        cmbCliente.setSelectedIndex(0);
    }
    
    private void atualizarTabela() {
        Object selO = cmbObjetivo.getSelectedItem();
        int filtroObjetivo = (selO instanceof Objetivo) ? ((Objetivo) selO).getObjetivoId() : -1;

        Object selC = cmbCliente.getSelectedItem();
        int filtroCliente = (selC instanceof Cliente) ? ((Cliente) selC).getClienteId() : -1;

        MembroGrupoModel model = new MembroGrupoModel();
        associacoes = model.liste(filtroObjetivo, filtroCliente);

        carregarTabela();
        linhaSelecionada = -1;
        controlarBotoes();
    }
    
    private void carregarTabela() {
        DefaultTableModel tbl = (DefaultTableModel) tblMembroGrupo.getModel();
        tbl.setRowCount(0);

        for (MembroGrupoModel mg : associacoes) {
            tbl.addRow(new Object[]{
                mg.getNomeObjetivo(),
                mg.getNomeCliente()
            });
        }
    }
    
    private void controlarBotoes() {
        boolean podeGravar = (cmbObjetivo.getSelectedItem() instanceof Objetivo) 
                           && (cmbCliente.getSelectedItem() instanceof Cliente);
        
        btnGravar.setEnabled(podeGravar);
        btnRemover.setEnabled(linhaSelecionada != -1);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cmbObjetivo = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMembroGrupo = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        cmbCliente = new javax.swing.JComboBox<>();
        btnGravar = new javax.swing.JButton();
        btnRemover = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Objetivo");

        cmbObjetivo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        tblMembroGrupo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Objetivo", "Cliente"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblMembroGrupo);
        if (tblMembroGrupo.getColumnModel().getColumnCount() > 0) {
            tblMembroGrupo.getColumnModel().getColumn(0).setResizable(false);
            tblMembroGrupo.getColumnModel().getColumn(1).setResizable(false);
        }

        jLabel2.setText("Cliente");

        cmbCliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnGravar.setText("Gravar");
        btnGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGravarActionPerformed(evt);
            }
        });

        btnRemover.setText("Remover");
        btnRemover.setEnabled(false);
        btnRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(cmbObjetivo, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnGravar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnRemover)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cmbCliente, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 120, Short.MAX_VALUE)
                                .addComponent(btnCancelar)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbObjetivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGravar)
                    .addComponent(btnRemover)
                    .addComponent(btnCancelar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGravarActionPerformed
        Objetivo o = (Objetivo) cmbObjetivo.getSelectedItem();
        Cliente c = (Cliente) cmbCliente.getSelectedItem();

        if (o == null || c == null) {
            JOptionPane.showMessageDialog(this, "Selecione um objetivo e um cliente válidos.", "Atenção", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Evita duplicidade
        for (MembroGrupoModel mg : associacoes) {
            if (mg.getObjetivoId() == o.getObjetivoId() && mg.getClienteId() == c.getClienteId()) {
                JOptionPane.showMessageDialog(this, "Este cliente já está vinculado a este objetivo.");
                return;
            }
        }

        String msg = new MembroGrupoModel().vincule(o.getObjetivoId(), c.getClienteId());
        JOptionPane.showMessageDialog(this, msg);
        atualizarTabela();
    }//GEN-LAST:event_btnGravarActionPerformed

    private void btnRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverActionPerformed
        if (linhaSelecionada == -1) {
            JOptionPane.showMessageDialog(this, "Selecione uma associação para remover.");
            return;
        }

        int op = JOptionPane.showConfirmDialog(this,
                "Deseja realmente remover este vínculo?",
                "Confirmação",
                JOptionPane.YES_NO_OPTION);

        if (op == JOptionPane.YES_OPTION) {
            MembroGrupoModel mg = associacoes.get(linhaSelecionada);
            String msg = new MembroGrupoModel().desvincule(mg.getObjetivoId(), mg.getClienteId());
            JOptionPane.showMessageDialog(this, msg);
            atualizarTabela();
        }
    }//GEN-LAST:event_btnRemoverActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        cmbObjetivo.setSelectedIndex(0);
        cmbCliente.setSelectedIndex(0);
        linhaSelecionada = -1;
        atualizarTabela();
        controlarBotoes();
    }//GEN-LAST:event_btnCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFMembroGrupo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFMembroGrupo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFMembroGrupo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFMembroGrupo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFMembroGrupo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGravar;
    private javax.swing.JButton btnRemover;
    private javax.swing.JComboBox<String> cmbCliente;
    private javax.swing.JComboBox<String> cmbObjetivo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblMembroGrupo;
    // End of variables declaration//GEN-END:variables

}
