
package view;



import controller.Objetivo;
import controller.Cliente;
import model.MembroGrupoModel;
import model.ObjetivoModel;
import model.ClienteModel;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author if739
 */
public class JFMenbroGrupo extends javax.swing.JFrame {
    
    private ArrayList<Objetivo> objetivos;
    private ArrayList<Cliente> clientes;
    private ArrayList<MembroGrupoModel> associacoes;
    private int linhaSelecionada = -1;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JFMenbroGrupo.class.getName());

    /**
     * Creates new form JFMenbroGrupo
     */
    public JFMenbroGrupo() {
        initComponents();
        carregarCombos ();
        atualizarTabela();;
        controlarBotoes();

        // Listeners para filtro automático
        cmbObjetivo.addActionListener(e -> atualizarTabela());
        cmbCliente.addActionListener(e -> atualizarTabela());
        
    }
    
    //método para carregar os campos da tabela.
    private void carregarCombos() {
        // Carrega objetivos
        ObjetivoModel objModel = new ObjetivoModel();
        objetivos = objModel.liste();
        
        
        cmbObjetivo.removeAllItems();
        cmbObjetivo.addItem("Todos"); // item para filtro
        for (Objetivo o : objetivos) {
            cmbObjetivo.addItem(o);
        }

        // Carrega clientes
        ClienteModel cliModel = new ClienteModel();
        clientes = cliModel.liste();
        
        cmbCliente.removeAllItems();
        cmbCliente.addItem("Todos");
        for (Cliente c : clientes) {
            cmbCliente.addItem(c);
        }

        cmbObjetivo.setSelectedIndex(0);
        cmbCliente.setSelectedIndex(0);
    }
    
    private void atualizarTabela() {
        Object selO = cmbObjetivo.getSelectedItem();
        int filtroObjetivo = (selO instanceof Objetivo) ? ((Objetivo) selO).getObjetivoId() : -1;

        Object selC = cmbCliente.getSelectedItem();
        int filtroCliente = (selC instanceof Cliente) ? ((Cliente) selC).getClienteId() : -1;

        MembroGrupoModel model = new MembroGrupoModel();
        associacoes = model.liste(filtroObjetivo, filtroCliente);

        carregarTabela();
        linhaSelecionada = -1;
        controlarBotoes();
    }
    
    private void carregarTabela() {
        DefaultTableModel tbl = (DefaultTableModel) tblMenbroGrupo.getModel();
        tbl.setRowCount(0);

        for (MembroGrupoModel mg : associacoes) {
            tbl.addRow(new Object[]{
                mg.getNomeObjetivo(),
                mg.getNomeCliente()
            });
        }
    }
    
    private void controlarBotoes() {
        boolean podeGravar = (cmbObjetivo.getSelectedItem() instanceof Objetivo) 
                           && (cmbCliente.getSelectedItem() instanceof Cliente);
        
        btnGravar.setEnabled(podeGravar);
        btnRemover.setEnabled(linhaSelecionada != -1);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    //init
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cmbObjetivo = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMenbroGrupo = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        cmbCliente = new javax.swing.JComboBox();
        btnGravar = new javax.swing.JButton();
        btnRemover = new javax.swing.JButton();
        btnCanselar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Objetivo");

        cmbObjetivo.setModel(new javax.swing.DefaultComboBoxModel());
        cmbObjetivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbObjetivoActionPerformed(evt);
            }
        });

        tblMenbroGrupo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Objetivo", "Cliente"
            }
        ));
        tblMenbroGrupo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMenbroGrupoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblMenbroGrupo);

        jLabel2.setText("Cliente");

        cmbCliente.setModel(new javax.swing.DefaultComboBoxModel());
        cmbCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbClienteActionPerformed(evt);
            }
        });

        btnGravar.setText("Gravar");
        btnGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGravarActionPerformed(evt);
            }
        });

        btnRemover.setText("Remover");
        btnRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverActionPerformed(evt);
            }
        });

        btnCanselar.setText("Cancelar");
        btnCanselar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCanselarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbObjetivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmbCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(201, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(btnGravar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRemover)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCanselar)
                .addGap(0, 151, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbObjetivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGravar)
                    .addComponent(btnRemover)
                    .addComponent(btnCanselar))
                .addGap(12, 12, 12)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbObjetivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbObjetivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbObjetivoActionPerformed

    private void cmbClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbClienteActionPerformed

    private void btnGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGravarActionPerformed
        Objetivo o = (Objetivo) cmbObjetivo.getSelectedItem();
        Cliente c = (Cliente) cmbCliente.getSelectedItem();

        if (o == null || c == null) {
            JOptionPane.showMessageDialog(this, "Selecione um objetivo e um cliente válidos.", "Atenção", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Evita duplicidade
        for (MembroGrupoModel mg : associacoes) {
            if (mg.getObjetivoId() == o.getObjetivoId() && mg.getClienteId() == c.getClienteId()) {
                JOptionPane.showMessageDialog(this, "Este cliente já está vinculado a este objetivo.");
                return;
            }
        }

        String msg = new MembroGrupoModel().vincule(o.getObjetivoId(), c.getClienteId());
        JOptionPane.showMessageDialog(this, msg);
        atualizarTabela();
    }//GEN-LAST:event_btnGravarActionPerformed

    private void btnRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverActionPerformed
        if (linhaSelecionada == -1) {
            JOptionPane.showMessageDialog(this, "Selecione uma associação para remover.");
            return;
        }

        int op = JOptionPane.showConfirmDialog(this,
                "Deseja realmente remover este vínculo?",
                "Confirmação",
                JOptionPane.YES_NO_OPTION);

        if (op == JOptionPane.YES_OPTION) {
            MembroGrupoModel mg = associacoes.get(linhaSelecionada);
            String msg = new MembroGrupoModel().desvincule(mg.getObjetivoId(), mg.getClienteId());
            JOptionPane.showMessageDialog(this, msg);
            atualizarTabela();
        }
    }//GEN-LAST:event_btnRemoverActionPerformed

    private void btnCanselarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCanselarActionPerformed
        cmbObjetivo.setSelectedIndex(0);
        cmbCliente.setSelectedIndex(0);
        linhaSelecionada = -1;
        atualizarTabela();
        controlarBotoes();
    }//GEN-LAST:event_btnCanselarActionPerformed

    private void tblMenbroGrupoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMenbroGrupoMouseClicked
        linhaSelecionada = tblMenbroGrupo.getSelectedRow();
        controlarBotoes();
    }//GEN-LAST:event_tblMenbroGrupoMouseClicked

      
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new JFMenbroGrupo().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCanselar;
    private javax.swing.JButton btnGravar;
    private javax.swing.JButton btnRemover;
    private javax.swing.JComboBox cmbCliente;
    private javax.swing.JComboBox cmbObjetivo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblMenbroGrupo;
    // End of variables declaration//GEN-END:variables
}
